name: pokedex
description: "Code challenge para Flutter Developers."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  go_router: ^13.0.1
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.2
  flutter_native_splash: ^2.4.1
  sembast: ^3.7.5
  sembast_web: ^2.4.0+4
  path_provider: ^2.1.1
  path: ^1.9.0
  country_flags: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  analyzer: ^5.13.0
  flutter_launcher_icons: ^0.14.1
  mockito: ^5.4.4

flutter_launcher_icons:
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: LibreFranklin
      fonts:
        - asset: assets/fonts/LibreFranklin-Light.ttf
        - asset: assets/fonts/LibreFranklin-LightItalic.ttf
          style: italic
        - asset: assets/fonts/LibreFranklin-Regular.ttf
        - asset: assets/fonts/LibreFranklin-Italic.ttf
          style: italic
        - asset: assets/fonts/LibreFranklin-Medium.ttf
        - asset: assets/fonts/LibreFranklin-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/LibreFranklin-Bold.ttf
        - asset: assets/fonts/LibreFranklin-BoldItalic.ttf
          style: italic

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf

  generate: true
